### PR TITLE
update ID docs

### PR DESCRIPTION
**Pull request by graingert**
specifically legal/chosen name not matching or no ID.

### CODE REVIEW

**Comment by mxsasha** [comment]
👍

**Comment by mxsasha** [comment]
Thanks for refining this :)

**Comment by graingert** [comment]
might also be worth considering something about middle/other names.

maybe lowering the "requirement" of ID to suggestion and doing a few slides about it in the actual event.

**Comment by graingert** [comment]
I'm going to merge this in, but happy to accept more wording updates, on this topic or otherwise.

**Pull request merged**
